DATASET:
  TRAIN: "-"
  VAL: "-"
  NAMES: "configs/coco.names"
MODEL:
  NC: 80
  INPUT_WIDTH: 128
  INPUT_HEIGHT: 128
TRAIN:
  LR: 0.001
  THRESH: 0.25
  WARMUP: true
  BATCH_SIZE: 96
  END_EPOCH: 300
  MILESTIONES:
    - 100
    - 200
    - 250
